### ISSUE TITLE
Default Server not Saving in v 2.2

### ISSUE THREAD

**Issue by pwadenz** [ninxsoft/JamfProSwitcher#5] opened 2021-11-22 02:13 UTC
Thanks for continued development! I just installed 2.2 and notice that if I set a different default server, it does not switch to this domain when I open Jamf Admin. If I quit and relaunch the app, it also does not save or remember any default server  (as indicated by a green tick). I switched back to version 2.1.1 and don't face the issue. Perhaps an auto saving issue on quit again?

**Comment by ninxsoft** [comment] 2021-11-22 13:04
This is why I should probably write some Unit Tests!

The issue is that I accidentally changed the path to look for:

`~/Library/Containers/Jamf Pro Switcher/Data/Library/Preferences/com.jamfsoftware.jss.plist`

instead of:

`~/Library/Preferences/com.jamfsoftware.jss.plist`

This is fixed in https://github.com/ninxsoft/JamfProSwitcher/commit/fc65210883e7ca94f025fb725bbfed1133a18f19

New release incoming!

**Closed as completed** 2021-11-22 13:10 UTC

**Comment by pwadenz** [comment] 2021-11-22 18:04
Confirmed all working as expected in 2.2.1 - thanks!
